### ISSUE TITLE
tree.pdf output clarification

### ISSUE THREAD

**Issue by Daliya-K** [QiuyuLian/CITE-sort#1]
Thank you for developing this method, it looks quite interesting!
I ran CITEsort on the PBMC_2k example dataset, you can see the output attached. 
I have several questions:
1. What represent the "**(2|2)**", "**(2|3)**", etc. in the inner nodes?
 0_CD3
Num: 1966
**(2|2)**

2. What represent the **numbers next to the black and red arrows**? Do they represent the same as the **numbers in the green leaf nodes** (In bold below) ?
8_leaf
CD154: **1.43**
CD4: **0.39**
CD56: **-0.28**
CD3: **-0.9**
CD19: **0.06**
CD14: **2.42**
CD11c: **2.11**
CD8a: **-0.57**
CD16: **-0.41**
CD127: **-0.25**

3. How to **reproduce the histograms** with the two parts after bi-partition highlighted from the biorXiv publication?

4. I have also tried to run CITEsort on a CITEseq dataset with 291 ADT features, and the tree.pdf output is unreadable. Is it possible to add **options for more compact plot outputs**?

Thank you!

[tree.pdf](https://github.com/QiuyuLian/CITE-sort/files/4695534/tree.pdf)

**Comment by QiuyuLian** [comment]
Hi Daliya-K, 
Thanks for using CITE-sort! A point-by-point response is provided below.
1. As you see, there are three rows in each inner node. 
    "n_marker(s)": **n** is the node ID, which is obtained by Breath First Search. **marker(s)**, the surface markers next to the ID, is the subspace selected to subdivide the current population.
    "Num: xxx": is the number of droplets in current population.
    "(a|b)": **b** denotes the number of components determined by BIC in the selected surface marker subspace. **a** denotes the number of component-complexes after merging with a certain threshold. Generally, a <= b. a = b when all components can not be merged with current threshold.
2. The numbers next to the arrows denote the mean of the selected markers in the partition the arrow stands for. In leaf nodes, the means of all markers  are marked. So, you are right. The numbers next to arrows and the numbers in leaf nodes both denote the mean values of markers in certain populations. As CITE-sort takes CLR-transformed values as input, the numbers could be positive or negative. 
3. I made a tutorial about plotting histograms. Please check the AnalysisTutorial.ipynb file.
4. Thanks for your good advice. I have add this option for compact plot outputs, which just omit the mean values in leaf nodes. I have dealt with several datasets with over 100 ADTs too. I noticed there are a handful of ADTs that are quite discrete. In my view, they may not capture real or strong biology signals. CITE-sort skips this kind of markers in current version, as GMM could not adapt to discrete values. I would suggest checking the marker distributions with CLR-transformed values in advance. Removing noisy surface markers and feeding filtered data to CITE-sort could also help simplifying the output tree.

Best,
Qiuyu

**Comment by Daliya-K** [comment]
Hi Qiuyu,

Thanks so much for the full explanation, and sorry for the late reply! 
Best,
Daliya
