### ISSUE TITLE
AttributeError - Namespace object has no attribute CLRTransder

### ISSUE THREAD

**Issue by tojojames** [QiuyuLian/CITE-sort#2]
Quick fix can be Changing line 42 of file preCITEsort.py:
"if args.CLRTransder:" to "if args.CLR:" can help to run the python preCITEsort.py correctly with arguments.

**Comment by QiuyuLian** [comment]
Hi James,

Thanks so much for pointing this out! 
I have fixed it now. 

Best,
Qiuyu

**Comment by tojojames** [comment]
I have tested the above fix.
