### ISSUE TITLE
Simulated datasets

### ISSUE THREAD

**Issue by sorjuela** [QiuyuLian/CITE-sort#3]
Hi @QiuyuLian ,

Where can I find the code you used to generate the simulations described in your paper?
https://academic.oup.com/bioinformatics/article/36/Supplement_1/i542/5870491#205479414

Best,
Stephany

**Comment by QiuyuLian** [comment]
Hi Stephany,

Many thanks for reaching out to me. 
Unfortunately, I don't have the simulation code currently. It was contributed by my collaborator Hongyi. Please contact him by hongyi.xin@sjtu.edu.cn for the code.

Best,
Qiuyu
